services:
  auth_db:
    image: postgres:17.6-alpine
    container_name: auth-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      PGPORT: ${AUTH_DB_PORT}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./auth_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "${AUTH_DB_PORT}"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        tag: "theatre-db"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  auth_app:
    container_name: auth-app
    build:
      context: ./
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./:/opt/app
    depends_on:
      - auth_redis
      - auth_db
      - jaeger
    logging:
      driver: "json-file"
      options:
        max-size: "10m"     # rotate when a log reaches 10MB
        max-file: "3"       # keep last 3 files
        tag: "auth_app"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth_app:8001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  auth_redis:
    image: redis:8.2.2-alpine
    container_name: auth-redis
    env_file:
      - .env
    ports:
      - "${AUTH_REDIS_PORT}:${AUTH_REDIS_PORT}"
    command: ["redis-server", "--save", "60", "1"]
    volumes:
      - auth_redis_data:/data
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        tag: "redis"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"

volumes:
  auth_db_data:
  auth_redis_data:

networks:
  app-network:
    driver: bridge